name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        linter:
          - flake8 --config=setup.cfg
          - black --check .
          - pyupgrade --py3-plus `find . -name "*.py"`
          - isort -c -vb
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt
    - run: ${{ matrix.linter }}
